### PR TITLE
Expose ElasticSearch configuration option in define

### PR DESCRIPTION
**Pull request by yoavlt**
Now, users can use custom configuration.

### CODE REVIEW

**Comment by Zatvobor** [comment]
Nice. Thanks

**Comment by Zatvobor** [comment]
Interesting, may I ask you to publish here a brief structure of DSL you have. So that, I would see why this improvements work for you or maybe we have to consider an solution to provide a better way for handling cases like that.

**Comment by yoavlt** [comment]
I want to switch configuration using separated configuration files of ElasticSearch depending on environment. But its interface is not expose configuration arguments and internal library doesn't use like `Application.get_env/2`. So, I added configuration argument in it.

**Comment by Zatvobor** [comment]
Yeah, I see. Thanks for details.

**Comment by Zatvobor** [comment]
I have created an issue (https://github.com/Zatvobor/tirexs/issues/169). This is about accessing URI settings through application's environment. This is definitely what we need.

**Comment by yoavlt** [comment]
@Zatvobor Great! Thanks!

**Comment by Zatvobor** [comment]
Available for review, here https://github.com/Zatvobor/tirexs/pull/170. Let me know if something wrong there. Thanks.

**Pull request closed without merging**
