### PR TITLE
Add :error pattern match for Tirexs.HTTP

### PR DESCRIPTION
**Pull request by matrinox**
This could happen when elasticsearch is down

### CODE REVIEW

**Comment by Zatvobor** [comment]
Hey @matrinox. Could you please provide an integration spec for this?

Thanks

**Comment by matrinox** [comment]
@Zatvobor done, added 2 small tests

**Comment by Zatvobor** [comment]
awesome. Thanks

**Comment by loganhenson** [comment]
this will be great to have, definitely ran into it almost immediately 😄

**Comment by Zatvobor** [comment]
got it

**Comment by OpakAlex** [comment]
this is good.

**Comment by Zatvobor** [comment]
@matrinox, thanks. Love it.

**Pull request merged**
