### PR TITLE
support 6.6.2 ES

### PR DESCRIPTION
**Pull request by OpakAlex**

### CODE REVIEW

**Comment by joneslee85** [comment]
@Zatvobor wondering if you could review this PR?

**Comment by OpakAlex** [comment]
@joneslee85 you can point to this branch into your mix file.

**Comment by joneslee85** [comment]
@OpakAlex yes that's what I do but I do hope it is get merged and officially supported

**Comment by OpakAlex** [comment]
we will try to merge it.

**Comment by joneslee85** [comment]
@OpakAlex because we adopt this at work, it would be great if it could be supported. If there is anything I could help with maintenance of the package, please let me know.

**Comment by OpakAlex** [comment]
In general it's no so a lot of changes with master, only issue with index create API, ES changed some fields. but for search master works good for 6.6.2 same as this branch. And master contains more features then new ES support. This why we thinking so long to merge this branch to master, and forgot support old ES versions.

**Pull request merged**
