### PR TITLE
call appropriate Tirexs.HTTP.post/3 function

### PR DESCRIPTION
**Pull request by kenta-aktsk**
#222

### CODE REVIEW

**Comment by Zatvobor** [comment]
👍 wanna to review it ASAP.

**Comment by Zatvobor** [comment]
@kenta-aktsk May I ask you to provide some sort of tests? That would be great to specify this changes. Thanks.

**Comment by kenta-aktsk** [comment]
@Zatvobor Got it. I will send it tomorrow or next week.

**Comment by kenta-aktsk** [comment]
@Zatvobor I added test to confirm settings is generated successfully.

**Pull request merged**
