### PR TITLE
Add aggregations to search result

### PR DESCRIPTION
**Pull request by Zatvobor**

### CODE REVIEW

**Comment by Zatvobor** [comment]
hey @gmalkas. Rebasing to the recent version is needed.

**Comment by gmalkas** [comment]
@Zatvobor Done! I was just hacking around to get it to work (and I did), that's why I stayed in `master`. I was planning to put it in a separate branch before creating a PR but you were quicker :)

Thanks!

**Comment by gmalkas** [comment]
@Zatvobor actually, let me create different branches (one for missing dependencies and one for aggregations) because it's kinda messy right now. Makes sense?

**Comment by Zatvobor** [comment]
extracted to another PR, #144

**Pull request closed without merging**
