### PR TITLE
Adapted for Elixir v1.0

### PR DESCRIPTION
**Pull request by alPacino**
Hey guys. I've made some changes for adaptation Tirexs for Elixir 1.0.

README was fixed too. The second code sample (mapping) doesn't work after populating an index. You show define mapping first. Otherwise ElasticSearch will do it for you automatically. But in case of auto-mapping you can't change mapping by your own. You will get errors like:

{:error, 400, "{\"error\":\"MergeMappingException[Merge failed with failures {[mapper [tags] has different index_analyzer, mapper [title] has different index_analyzer]}]\",\"status\":400}"}

Tests passing.

Hope these changes will be helpful for others.

### CODE REVIEW

**Comment by Zatvobor** [comment]
Yeah, for sure. I'll handle it. Thanks for contribution!

**Comment by Zatvobor** [comment]
hey @alPacino. I really like it. Could you please merge some tiny conflicts so that I can merge it automatically. A million thanks.

**Comment by alPacino** [comment]
Hey, Alex. It's Rodion :) Actually I've merged branch elixir-1.0 into master w/o any conflicts. Hope you can merge my master into yours w/o problems also. Otherwise will fix that :)

**Comment by Zatvobor** [comment]
Hey! As you can see I can merge this pull request automatically due to some small conflicts. I guess you should pull my recent changes from `Zatvobor/master` that is tagged with `v.0.5.1`. BTW, let's make the hangout instead. Thanks again.

**Comment by alPacino** [comment]
Hi. Sorry for that. Pulled your tag 0.5.1 into my repo, merged and pushed. You can try again.

**Pull request closed without merging**
