### PR TITLE
Support for bulk update API

### PR DESCRIPTION
**Pull request by matrinox**
Refactor - be more similar to bulk update API

### CODE REVIEW

**Comment by matrinox** [comment]
This is just a quick fix to get it to work in the app I'm working on. This adds bulk update (before it's just single update via bulk API). It's in production and it works for my limited use case; I'm not sure if I broke existing headers.

My long-term plan is to refactor this so that index/create/update/destroy create a tuple of maps exactly like the one used to send to elasticsearch's bulk API, leaving the bulk method to just encode and send request. This reduces flexibility but makes coding much cleaner IMO

**Comment by Zatvobor** [comment]
Awesome. Will ping you back after review. Thanks

**Comment by OpakAlex** [comment]
@matrinox, we will merge it, after merge update elixir branch, then you will push updates.

**Comment by OpakAlex** [comment]
@matrinox rebase master, and fix warnings. Thanks!

**Comment by matrinox** [comment]
Your 0.8.x I think has fixed bulk update so this is no longer needed

**Pull request closed without merging**
