### PR TITLE
Support elasticsearch 5

### PR DESCRIPTION
**Pull request by Zatvobor**
Make the lib ready to work both on 2.x and 5.x ES branches

### CODE REVIEW

**Comment by OpakAlex** [comment]
@Zatvobor i will check ;)

**Comment by Zatvobor** [comment]
@OpakAlex any updates here?

**Comment by OpakAlex** [comment]
will do, i don't have time for this now.

**Comment by OpakAlex** [comment]
@Zatvobor we can not use matrix for tests. They changed api for 5 version. So we can migrate or stay in old.

**Comment by ryancammer** [comment]
I saw failing tests tonight when I ran mix test, and I'm using ES 5.5.1. This is because I'm also using Elixir 1.5.1, and there's a warning about Elixir versions. I'm thinking about embarking on a quest to get these tests passing, and get ES 5.5 supported, but before I do, what's the vision for this project? Are you wanting to support old and new versions of Elixir? How difficult you think it is to provide support for ES 5.x?

**Comment by OpakAlex** [comment]
6.6.2 branch fixes a lot of issues.

**Pull request closed without merging**
