### PR TITLE
Add Parameters for Bool Method

### PR DESCRIPTION
**Pull request by MaximeRDY**
Hi there, 

I've added the possibility to add some parameters when you do a bool request. 
Like `minimum_should_match` or `boost`. 

What do you think ? 

cf: documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html

### CODE REVIEW

**Comment by MaximeRDY** [comment]
any news ?

**Comment by OpakAlex** [comment]
@MaximeRDY looks it works.yes?

**Comment by Zatvobor** [comment]
I'll manage it ASAP. Sorry for delay.

**Comment by MaximeRDY** [comment]
@OpakAlex I've test it. For me, it works :-) 
But i'm a beginner in Elixir so I think it needs code review :-)

**Comment by OpakAlex** [comment]
забей хуй, я втыкну

**Pull request merged**
