### PR TITLE
`V0.8.0-beta2` candidate

### PR DESCRIPTION
**Pull request by Zatvobor**
Scope:
- [x] `Tirexs.ENV`  - is to made up a main ES `%URI{}` from `System.get_env("ES_URI")` or `Application.get_env/2` and finally from `Mix.Config.config/2`
- [x] `Tirexs.load_file(file)` - Utility for managing code compilation, code evaluation and code loading.
- [ ] `Tirexs.Resources` module (rebasing certain responsibilities between `Tirexs.ElasticSearch` and `Tirexs.Manage` modules), #182 
- [ ] warning: `Tirexs.Elasticsearch.refresh/2` is deprecated, please use `Tirexs.Resources._refresh/2` instead
- [ ] warning: `Tirexs.Elasticsearch.aliases/2` is deprecated, please use `Tirexs.Resources._aliases/2` instead
- [x] `Tirexs.HTTP` bang functions: `head!`, `get!`, `post!`, `put!`, `delete!` #189 
- [x] First-class documentation for `Tirexs`, `Tirexs.HTTP` and their functions, #12
- [x] Remove using `JSX.encode|decode` in favor of `HTTP.encode|decode`, #180
- [x] `Tirexs.HTTP` functions w/ REST parameters: `head`, `get`, `delete`, `put`, `post`, `url`, #189 
- [x] `Tirexs.HTTP` - `put`, `post`, w/ body (maps and lists types are supported) #189 
- [ ] Aggregation in favor of Facets, #183 
- [ ] warning: `Tirexs.Elasticsearch.delete/3` is deprecated, please use `Tirexs.HTTP.delete/3` instead
- [ ] warning: `Tirexs.Elasticsearch.config/0` is deprecated, please use `Tirexs.get_uri_env/0` instead
- [ ] warning: `Tirexs.Elasticsearch.post/3` is deprecated, please use `Tirexs.HTTP.post/3` instead
- [ ] warning: `Tirexs.Elasticsearch.get/2` is deprecated, please use `Tirexs.HTTP.get/2` instead
- [ ] warning: `Tirexs.Elasticsearch.put/3` is deprecated, please use `Tirexs.HTTP.put/3` instead
- [ ] warning: `Tirexs.Elasticsearch.head/2` is deprecated, please use `Tirexs.HTTP.head/2` instead

_(will be changed...)_

### CODE REVIEW

**Comment by Zatvobor** [comment]
@kpanic: once again, needs code review )

**Comment by kpanic** [comment]
@Zatvobor I will give at look during the next week ;)

**Comment by kpanic** [comment]
@Zatvobor sorry, I had not time :)

**Comment by Zatvobor** [comment]
It's ok. Also, that would be great to get a feedback from you about recent changes and what's still missing... Thanks.

**Pull request merged**
