### PR TITLE
fix encoding issue

### LINKED ISSUE #227: get unicode strings
when I do a get on a specific ID some fields are unprintable yet valid binary strings. when I do a search for the same object, the same fields are now printable. I've narrowed it down to fields that contain "'" (0x2019) or "—" (0x2014)

### PR DESCRIPTION
**Pull request by markschultz**
fixes #227

### CODE REVIEW

**Comment by Zatvobor** [comment]
Nice. Could you please provide a few specs for the issue. Thanks.

**Comment by Zatvobor** [comment]
It works as expected
```bash
iex(7)> Tirexs.HTTP.put("/index/type/1", [MeetingTitle: "Planner— A", Id: 1])
{:ok, 200,
 %{_id: "1", _index: "index", _shards: %{failed: 0, successful: 1, total: 2},
   _type: "type", _version: 2, created: false}}
iex(8)> {:ok, 200, %{_source: %{MeetingTitle: meeting_title}}} = Tirexs.HTTP.get("/index/type/1")
{:ok, 200,
 %{_id: "1", _index: "index", _source: %{Id: 1, MeetingTitle: "Planner— A"},
   _type: "type", _version: 2, found: true}}
```

**Comment by markschultz** [comment]
going on vacation sorry. just saw your spec and its exactly what I was going to try to do, thanks!

**Comment by markschultz** [comment]
ok, tests are working

**Comment by markschultz** [comment]
Hi, what is preventing this from merging? Is there anything else you need from me?

**Comment by Zatvobor** [comment]
Nope. Going to manage it on this week. Sorry for delay.

**Pull request merged**
