### PR TITLE
Settings in mappings, #159

### PR DESCRIPTION
**Pull request by kpanic**
The purpose of this PR, would be to have the possibility to create the settings together with the mappings in one shot.
Reason is that, if I want to create an autocomplete custom analyzer used in the mappings via macros

### CODE REVIEW

**Comment by kpanic** [comment]
Hi @Zatvobor :) This would be the approach.
Please let me know if https://github.com/Zatvobor/tirexs/pull/162/files#diff-5db5885e4f4542f1a8924bb6e82d8cdeR14 is a good elixir practice.
I am still learning...
If this approach would be good, I'll document it thanks and ciao!

**Comment by kpanic** [comment]
@Zatvobor there's still one bit missing, I forgot to adapt `create_resource` in mapping ;)

**Comment by Zatvobor** [comment]
Awesome. Will review this one.

**Comment by kpanic** [comment]
Thanks @Zatvobor, however I want to write an acceptance test first ;) You can obviously review what's here although!

**Comment by kpanic** [comment]
@Zatvobor should be ready for review

**Comment by Zatvobor** [comment]
Sure. Let's take the time.

**Comment by kpanic** [comment]
@Zatvobor finally this is ready for review, I spotted a not consistent behaviour thanks to the acceptance test ;)
More context on this "combo" (settings and mappings) in this interesting article https://qbox.io/blog/multi-field-partial-word-autocomplete-in-elasticsearch-using-ngrams -- especially `The Analyzers` section
Thank you!

**Comment by Zatvobor** [comment]
Amazing )

**Comment by Zatvobor** [comment]
Conflicts are already resolved and pushed into `kpanic-settings-in-mappings`. This branch is based on `v0.x.x` branch as I want to release this awesome feature under *v0.8.0*.

https://github.com/kpanic/tirexs/pull/1 contains already resolved conflicts.

**Comment by kpanic** [comment]
New PR https://github.com/Zatvobor/tirexs/pull/172 open against `v0.x.x`

**Pull request closed without merging**
